-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PortfolioData.Object exposing (Classifications(..), Experience_classifications(..), Experiences(..))


type Classifications
    = Classifications


type Experience_classifications
    = Experience_classifications


type Experiences
    = Experiences
