-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PortfolioData.ScalarCodecs exposing (Date, Id, codecs)

import Json.Decode as Decode exposing (Decoder)
import PortfolioData.Scalar exposing (defaultCodecs)


type alias Date =
    PortfolioData.Scalar.Date


type alias Id =
    PortfolioData.Scalar.Id


codecs : PortfolioData.Scalar.Codecs Date Id
codecs =
    PortfolioData.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        }
